dic_labels = {
    "cpi": ["CPI:当月同比", "M"],
    "pmi_neo": ["PMI:新出口订单", "M"],
    "pmi_sv": ["服务业PMI", "M"],
    "pmi_p": ["PMI:生产", "M"],
    "m&ltl_yoy": ["中长期贷款余额同比", "M"],
    "r007": ["7天回购利率", "D"],
    "neqf": ["新成立基金份额:偏股型", "D"],
    "mrb": ["融资买入额", "D"],
    "usdcnh_spot": ["美元兑人民币即期汇率", "D"],
    "tby_10y": ["10年期国债收益率", "D"],
    "us_tby_10y": ["美国10年期国债收益率", "D"],
    "s&p500_vix": ["VIX恐慌指数", "D"],
    "pb": ["市净率", "D"],
    "pe_ttm": ["市盈率(TTM)", "D"],
    "dy_ttm": ["股息率(TTM)", "D"],
    "ic_cfe": ["年化基差收益率:IC", "D"],
}

dic_features = {
    "cpi": ["CPI:当月同比", "M"],
    "pmi_neo": ["PMI:新出口订单", "M"],
    "pmi_sv": ["服务业PMI", "M"],
    "pmi_p": ["PMI:生产", "M"],
    "m&ltl_yoy": ["中长期贷款余额同比", "M"],
    "r007": ["7天回购利率", "W"],
    "neqf": ["新成立基金份额:偏股型", "W"],
    "mrb": ["融资买入额", "W"],
    "usdcnh_spot": ["美元兑人民币即期汇率", "W"],
    "tby_diff": ["中美10年期国债收益率差值", "W"],
    "tby_winda_spread": ["股债性价比", "W"],
    "s&p500_vix": ["VIX恐慌指数", "W"],
    "pb": ["市净率", "W"],
    "pe_ttm": ["市盈率(TTM)", "W"],
    "sma": ["sma", "D"],
    "bbi": ["bbi", "D"],
    "cci": ["cci", "D"],
    "kdj": ["kdj", "D"],
    "cmo": ["cmo", "D"],
    "roc": ["roc", "D"],
    "ic_cfe": ["年化基差收益率:IC", "D"],
    "volume_price_mom": ["成交量价格动量", "D"],
}

dic_labels2features = {
    "cpi": ["not_change", {}],
    "pmi_neo": ["not_change", {}],
    "pmi_sv": ["not_change", {}],
    "m&ltl_yoy": ["not_change", {}],
    "pmi_p": ["pct_change", {}],
    "r007": ["day2week_ewm", {"freq": "B", "span": 5, "if_intra_week": True, "intra_span": 8}],
    "neqf": ["day2week_ewm", {"freq": "B", "span": 5, "if_intra_week": False}],
    "mrb": ["day2week_ewm", {"freq": "B", "span": 5, "if_intra_week": False}],
    "usdcnh_spot": ["day2week_ewm", {"freq": "B", "span": 5, "if_intra_week": False}],
    "tby_diff": [
        "day2week_ewm",
        {"label1": "tby_10y", "label2": "us_tby_10y", "freq": "B", "span": 5, "if_intra_week": False},
    ],
    "tby_winda_spread": [
        "day2week_ewm",
        {"label1": "tby_10y", "label2": "dy_ttm", "freq": "B", "span": 5, "if_intra_week": False},
    ],
    "s&p500_vix": ["day2week_ewm", {"freq": "B", "span": 5, "if_intra_1week": False}],
    "pb": ["day2week_ewm", {"freq": "D", "span": 7, "if_intra_week": False}],
    "pe_ttm": ["day2week_ewm", {"freq": "D", "span": 7, "if_intra_week": False}],
    "sma": ["get_sma_idc", {"timeperiod": 20}],
    "bbi": ["get_bbi_idc", {"tp1": 3, "tp2": 6, "tp3": 12, "tp4": 24}],
    "cci": ["get_cci_idc", {"timeperiod": 10}],
    "kdj": ["get_kdj_idc", {"fastk_period": 9, "slowk_period": 3, "slowd_period": 3}],
    "cmo": ["get_cmo_idc", {"timeperiod": 10}],
    "roc": ["get_roc_idc", {"timeperiod": 10}],
    "ic_cfe": ["get_bbands_iccfe", {"timeperiod": 20, "nbdevup": 1, "nbdevdn": 1}],
    "volume_price_mom": ["get_vol_mom_idc", {}],
}

dic_label2feature_post = {
    "tby_winda_spread": ["get_bbands_idc", {"timeperiod": 52, "nbdevup": 2, "nbdevdn": 2, "factor_name": "features"}],
    "tby_diff": ["get_sma_idc", {"timeperiod": 26, "if_resample": False, "column_name": "features"}],
    "s&p500_vix": ["get_bbands_idc", {"timeperiod": 26, "nbdevup": 1, "nbdevdn": 1, "factor_name": "features"}],
    "neqf": ["get_sma_idc", {"timeperiod": 8, "if_resample": False, "column_name": "features"}],
    "mrb": ["get_sma_idc", {"timeperiod": 8, "if_resample": False, "column_name": "features"}],
    "usdcnh_spot": ["get_sma_idc", {"timeperiod": 52, "if_resample": False, "column_name": "features"}],
}


dic_feature2signals = {
    "cpi": ["mom_rule", {"indicator_name": "features", "isMTM": True}],
    "pmi_neo": ["mom_rule", {"indicator_name": "features", "isMTM": True}],
    "pmi_sv": ["mom_rule", {"indicator_name": "features", "isMTM": True}],
    "pmi_p": ["mom_rule", {"indicator_name": "features", "isMTM": True}],
    "m&ltl_yoy": ["mom_rule", {"indicator_name": "features", "isMTM": True}],
    "r007": ["mom_rule", {"indicator_name": "features", "isMTM": False}],
    "neqf": ["positional_rule_reference_line", {"indicator_name": "sma", "reference_line": "features"}],
    "mrb": ["positional_rule_reference_line", {"indicator_name": "sma", "reference_line": "features"}],
    "usdcnh_spot": ["positional_rule_reference_line", {"indicator_name": "sma", "reference_line": "features"}],
    "tby_diff": [
        "positional_rule_reference_line",
        {"indicator_name": "sma", "reference_line": "features", "threshold": 0},
    ],
    "tby_winda_spread": [
        "positional_rule_bands",
        {"upperband": "upperband", "lowerband": "lowerband", "reference_line": "features", "isMTM": True},
    ],
    "s&p500_vix": [
        "positional_rule_bands",
        {"upperband": "upperband", "lowerband": "lowerband", "reference_line": "features", "isMTM": True},
    ],
    "pb": ["quantile_rule", {"rolling_window": 26, "threshold": 0.3}],
    "pe_ttm": ["quantile_rule", {"rolling_window": 26, "threshold": 0.3}],
    "sma": ["positional_rule_reference_line", {"indicator_name": "sma", "reference_line": "CLOSE", "threshold": 0}],
    "bbi": ["positional_rule_reference_line", {"indicator_name": "bbi", "reference_line": "CLOSE", "threshold": 0}],
    "cci": ["cross_rule", {"indicator_name": "cci", "value1": 100, "value2": -100}],
    "kdj": ["cross_rule", {"isValue": False, "ReferenceLine1": "slowk", "ReferenceLine2": "slowd"}],
    "cmo": ["positional_rule_value", {"indicator_name": "cmo", "isInverse": False}],
    "roc": ["positional_rule_value", {"indicator_name": "roc", "isInverse": False}],
    "ic_cfe": [
        "positional_rule_bands",
        {"upperband": "upperband", "lowerband": "lowerband", "reference_line": "CLOSE"},
    ],
    "volume_price_mom": ["volume_price_momentum_rule", {}],
}

dic_feature2value = {
    "cpi": {"feature_col": "features", "mode": "features"},
    "pmi_neo": {"feature_col": "features", "mode": "features"},
    "pmi_sv": {"feature_col": "features", "mode": "features"},
    "pmi_p": {"feature_col": "features", "mode": "features"},
    "m&ltl_yoy": {"feature_col": "features", "mode": "features"},
    "r007": {"feature_col": "features", "mode": "features", "inverse": True},
    "neqf": {"feature_col": "features", "mode": "features"},
    "mrb": {"feature_col": "features", "mode": "features"},
    "usdcnh_spot": {"feature_col": "features", "mode": "features"},
    "tby_diff": {"feature_col": "features", "mode": "features"},
    "tby_winda_spread": {"feature_col": "features", "mode": "features"},
    "s&p500_vix": {"feature_col": "features", "mode": "features"},
    "pb": {"feature_col": "features", "mode": "features", "inverse": True},
    "pe_ttm": {"feature_col": "features", "mode": "features", "inverse": True},
    "sma": {"feature_col": "sma", "mode": "features"},
    "bbi": {"feature_col": "bbi", "mode": "features"},
    "cci": {"feature_col": "cci", "mode": "features"},
    "kdj": {"mode": "kdj"},  # 自定义计算
    "cmo": {"feature_col": "cmo", "mode": "features"},
    "roc": {"feature_col": "roc", "mode": "features"},
    "ic_cfe": {"feature_col": "CLOSE", "mode": "features"},
    "volume_price_mom": {"mode": "volume_price_mom", "price_col": "CLOSE", "vol_col": "VOLUME"},  # 自定义计算
}
